name: Deploy to EC2

env:
  EC2_HOST: 54.180.115.6
  EC2_USER: ec2-user
  DEPLOY_PATH: /home/ec2-user

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > /tmp/id_rsa
          chmod 600 /tmp/id_rsa
          mv /tmp/id_rsa ~/.ssh/id_rsa
          ssh-keyscan ${{ env.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: ssh -o BatchMode=yes -T ${{ env.EC2_USER }}@${{ env.EC2_HOST }} exit

      - name: Deploy to EC2
        run: |
          # Copy build files to EC2
          scp -o StrictHostKeyChecking=no -r dist/* ${{ env.EC2_USER }}@${{ env.EC2_HOST }}:${{ env.DEPLOY_PATH }}

          # (Optional) Restart service if needed
          # ssh -o StrictHostKeyChecking=no ${{ env.EC2_USER }}@${{ env.EC2_HOST }} "sudo systemctl restart your-service-name"
